# Generated by Django 5.2.7 on 2025-10-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=32, verbose_name='话题名称')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('token', models.CharField(max_length=256, verbose_name='token')),
                ('token_expire', models.DateTimeField(blank=True, null=True, verbose_name='token 过期时间')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (0, '禁用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user-info',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(max_length=32, verbose_name='咨询标题')),
                ('image', models.TextField(blank=True, null=True, verbose_name='咨询图片')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='咨询链接')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核拒绝')], default=0, verbose_name='咨询状态')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('recommend_count', models.IntegerField(default=0, verbose_name='推荐数')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '咨询',
                'verbose_name_plural': '咨询',
                'db_table': 'news',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='推荐时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.news', verbose_name='咨询')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
                'db_table': 'recommend',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='评论时间')),
                ('depth', models.IntegerField(default=0, verbose_name='评论深度')),
                ('last_comment_time', models.DateTimeField(blank=True, null=True, verbose_name='最后评论时间')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='myapp.comment', verbose_name='父评论')),
                ('root_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='myapp.comment', verbose_name='根评论')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.news', verbose_name='咨询')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='收藏时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.news', verbose_name='咨询')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'collect',
            },
        ),
    ]
